#!/usr/bin/ruby
require 'package'

GLOBAL_SETTINGS = {
  :package => {
    :directory => "/var/teledrill"
  },
  :tdsurface => {
    :password => "scimitar1"
  },
  :debug => true
}
SETTINGS=GLOBAL_SETTINGS

if __FILE__ == $0
  for path in Dir.glob("packages/*")
    require path if File.exists? path and path =~ /rb$/
  end
  command = ARGV[0].intern
  the_package = lookup(ARGV[1].intern)
  eval("the_package.#{command}")
end
